"""Live Arena tournament automation."""

import modules.community.live_arena.swiss_repository  # noqa: F401
import modules.community.live_arena.swiss_provisional  # noqa: F401
import modules.community.live_arena.swiss_validation  # noqa: F401
from modules.community.live_arena.runtime_hooks import install as _install_runtime_hooks
from modules.community.live_arena.competition_repair import install as _install_repair
from modules.community.live_arena.competition_followup import install as _install_followup
from modules.community.live_arena.swiss_panel import install as _install_swiss
from modules.community.live_arena.swiss_runtime import install as _install_swiss_runtime
from modules.community.live_arena.swiss_manual_panel import install as _install_swiss_manual
from modules.community.live_arena.knockout_final import install as _install_knockout_final
from modules.community.live_arena.knockout_match_format import install as _install_knockout_match_format
from modules.community.live_arena.knockout_completion import install as _install_knockout_completion
from modules.community.live_arena.knockout_runtime import install as _install_knockout_runtime
from modules.community.live_arena.knockout_tiebreak import install as _install_knockout_tiebreak
from modules.community.live_arena.knockout_recap_repair import install as _install_knockout_recap_repair
from modules.community.live_arena.competition_operations_runtime import install as _install_competition_operations
from modules.community.live_arena.operations_ui_hardening import install as _install_operations_ui_hardening
from modules.community.live_arena.bye_support import install as _install_bye_support
from modules.community.live_arena.q1_random_pairing import install as _install_q1_random_pairing
from modules.community.live_arena.q1_bye_approval import install as _install_q1_bye_approval
from modules.community.live_arena.bye_action_snapshots import install as _install_bye_action_snapshots
from modules.community.live_arena.bye_ui import install as _install_bye_ui
from modules.community.live_arena.bye_manual_validation import install as _install_bye_manual_validation
from modules.community.live_arena.withdrawal_hardening import install as _install_withdrawal_hardening
from modules.community.live_arena.withdrawal_atomic import install as _install_withdrawal_atomic
from modules.community.live_arena.operations_correction_state import install as _install_operations_correction_state
from modules.community.live_arena.extension_confirmation import install as _install_extension_confirmation
from modules.community.live_arena.availability_ux import install as _install_availability_ux
from modules.community.live_arena.availability_reminder import install as _install_availability_reminder
from modules.community.live_arena.next_tournament import install as _install_next_tournament
from modules.community.live_arena.hall_of_fame import install as _install_hall_of_fame
from modules.community.live_arena.organizer_capacity_guard import install as _install_organizer_capacity_guard
from modules.community.live_arena.organizer_registration_hardening import install as _install_organizer_registration_hardening
from modules.community.live_arena.sheets_read_hardening import install as _install_sheets_read_hardening
from modules.community.live_arena.simulation_ux_hardening import install as _install_simulation_ux_hardening
from modules.community.live_arena.simulation_ux_finalizer import install as _install_simulation_ux_finalizer
from modules.community.live_arena.full_set_scoring import install as _install_full_set_scoring
from modules.community.live_arena.captains_table_quota_safe import install as _install_captains_table_quota_safe
from modules.community.live_arena.scheduling_resolution_ux import install as _install_scheduling_resolution_ux
from modules.community.live_arena.victory_ledger_link_guard import install as _install_victory_ledger_link_guard
from modules.community.live_arena.round_finish_refresh import install as _install_round_finish_refresh
from modules.community.live_arena.round_close_milestone_ux import install as _install_round_close_milestone_ux
from modules.community.live_arena.preview_message_guard import install as _install_preview_message_guard
from modules.community.live_arena.swiss_progression_controls import install as _install_swiss_progression_controls
from modules.community.live_arena.live_stage_render import install as _install_live_stage_render
from modules.community.live_arena.matchup_thread_ux import install as _install_matchup_thread_ux
from modules.community.live_arena.matchup_thread_result_copy import install as _install_matchup_thread_result_copy
from modules.community.live_arena.swiss_overview_persistence import install as _install_swiss_overview_persistence
from modules.community.live_arena.round_overview import install as _install_round_overview
from modules.community.live_arena.round_overview_migration import install as _install_round_overview_migration
from modules.community.live_arena.result_control_refresh import install as _install_result_control_refresh
from modules.community.live_arena.result_lifecycle_ux import install as _install_result_lifecycle_ux
from modules.community.live_arena.result_lifecycle_fallback import install as _install_result_lifecycle_fallback
from modules.community.live_arena.result_staff_override import install as _install_result_staff_override
from modules.community.live_arena.victory_ledger_final_refresh import install as _install_victory_ledger_final_refresh

_install_runtime_hooks()
_install_repair()
_install_followup()
_install_swiss()
_install_swiss_runtime()
_install_swiss_manual()
_install_knockout_final()
_install_knockout_match_format()
_install_knockout_completion()
_install_knockout_runtime()
_install_knockout_tiebreak()
_install_knockout_recap_repair()
_install_competition_operations()
_install_operations_ui_hardening()
_install_bye_support()
_install_q1_random_pairing()
_install_q1_bye_approval()
_install_bye_action_snapshots()
_install_bye_ui()
_install_bye_manual_validation()
_install_withdrawal_hardening()
_install_withdrawal_atomic()
_install_operations_correction_state()
_install_extension_confirmation()
_install_availability_ux()
_install_availability_reminder()
_install_next_tournament()
_install_hall_of_fame()
_install_organizer_capacity_guard()
_install_organizer_registration_hardening()
_install_sheets_read_hardening()
_install_simulation_ux_hardening()
_install_simulation_ux_finalizer()
_install_full_set_scoring()
_install_captains_table_quota_safe()
_install_scheduling_resolution_ux()
_install_victory_ledger_link_guard()
_install_round_finish_refresh()
_install_round_close_milestone_ux()
_install_preview_message_guard()
_install_swiss_progression_controls()
_install_live_stage_render()
_install_matchup_thread_ux()
_install_matchup_thread_result_copy()
_install_swiss_overview_persistence()
_install_round_overview()
_install_round_overview_migration()
_install_result_control_refresh()
_install_result_lifecycle_ux()
_install_result_lifecycle_fallback()
_install_result_staff_override()
_install_victory_ledger_final_refresh()